import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import NavBar from "@/components/NavBar/NavBar"
import Footer from "@/components/Footer/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Index - Burger King",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main className="flex min-h-screen flex-col items-center bg-[url('https://bkdelivery.co.id/static/website/img/BK_bg.jpg?5218847fa211')] bg-fixed bg-no-repeat">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
